### ISSUE TITLE
docs:add licence

### ISSUE THREAD

**Issue by hankadev** [FrancescoXX/contentbox#24]
### what's wrong with the documentation?

the repository should include the licence so it is clear whether others can use it or not. probably MIT or Apache?

@FrancescoXX have you decided which licence you wanna use? :thinking: 

### Add screenshots

n/a

### Record

- [X] I have checked the existing [issues](https://github.com/FrancescoXX/contentbox/issues)
- [X] I want to work on this issue

**Comment by FrancescoXX** [comment]
I'd like to do it MIT. wanna work on this? @hankadev

**Comment by hankadev** [comment]
@FrancescoXX yes, I would love to. opened a PR for it :muscle:
