### ISSUE TITLE
Bug:  Cards not clickable

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/contentbox#26]
### What happened?

the cards on the main page are not clickable

### Add screenshots

![image](https://github.com/FrancescoXX/contentbox/assets/18360871/f62a2945-8520-4607-ad29-d4ad0c85c912)

### Record

- [X] I have checked the existing [issues](https://github.com/FrancescoXX/contentbox/issues)
- [ ] I want to work on this issue

**Comment by holaliamewu** [comment]
I want to work on this.
can i go on with it?

**Comment by FrancescoXX** [comment]
fixed
