### ISSUE TITLE
feat: Links Embed

### ISSUE THREAD

**Issue by shvamabps** [FrancescoXX/contentbox#27]
### What feature?

Like in a markdown language, the links can be embedded.

### Add screenshots

![image](https://github.com/FrancescoXX/contentbox/assets/37547983/a546eb4f-30e8-47ad-bc36-45a580e90d1c)

### Record

- [X] I have checked the existing [issues](https://github.com/FrancescoXX/contentbox/issues)
- [ ] I want to work on this issue

**Comment by FrancescoXX** [comment]
they are already embedded, but I added an additional link on top

**Comment by shvamabps** [comment]
Sorry, didn't notice that, I looked at the link only.
