### ISSUE TITLE
docs: Automate fetching playlists from YouTube to ContentBox

### ISSUE THREAD

**Issue by oluwatobiss** [FrancescoXX/contentbox#30]
### Description

Instead of manually copying and pasting each YouTube video, use the YouTubePlaylist plugin to auto-fetch the playlists and display them as a gallery on the page.

### Example
[Demo of React plugin used to auto-fetch Youtube playlist](https://codesweetly.com/react-youtube-playlist#live-demo)

### Advantages

- Automate the process of adding videos to ContentBox.
- Make ContentBox's videos SEO-friendly.
- Publish on YouTube and Auto-synchronize to ContentBox instantly.

I would love to work on this issue.

### Add screenshots

Screenshot of my Docusaurus website using the same technique.

![React YouTube Playlist on CodeSweetly website](https://github.com/FrancescoXX/contentbox/assets/60105594/af3e768f-b153-4524-b072-c13aafcd23d1)

### Record

- [X] I have checked the existing [issues](https://github.com/FrancescoXX/contentbox/issues)
- [X] I want to work on this issue

**Comment by FrancescoXX** [comment]
@oluwatobiss I assignedd this to you, we might need this on  the main page (like  the podcast one )

https://contentbox.vercel.app/docs/podcast/

but generally speaking , i still want the single videos with some place to add context and text
