### ISSUE TITLE
feat: populate the DevRel section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/contentbox#39]
### What feature?

populate the devrel section with videos from the DevRel unlocked series

https://www.youtube.com/playlist?list=PLPoSdR46FgI7H0SVOqSS_bNaIep8RkVCT

### Add screenshots

a

### Record

- [X] I have checked the existing [issues](https://github.com/FrancescoXX/contentbox/issues)
- [ ] I want to work on this issue

**Comment by xkrishguptaa** [comment]
Can I work on this?

**Comment by Dun-sin** [comment]
is all this automatic yet? like others can create an account and add theirs?

**Comment by FrancescoXX** [comment]
there's still no "account" section. but there might be an issue (big one)

**Comment by FrancescoXX** [comment]
all the videos has been added
