### ISSUE TITLE
feat: populate the Web Dev section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/contentbox#40]
### What feature?

add the "building projects" section

https://www.youtube.com/playlist?list=PLPoSdR46FgI4K36elsmeoUynDUXhjvtEn

### Record

- [X] I have checked the existing [issues](https://github.com/FrancescoXX/contentbox/issues)
- [ ] I want to work on this issue

**Comment by paaggeli** [comment]
Hi, I've submitted a pull request #68  adding the first 5 videos. 
I left the remaining videos open for new contributors, considering it's a beginner-friendly task. 
Feel free to use my pull request as a guide, and don't hesitate to ask me if you have any problems.

**Comment by FrancescoXX** [comment]
thanks
