### ISSUE TITLE
feat: use FUNDING.yml

### ISSUE THREAD

**Issue by xkrishguptaa** [FrancescoXX/contentbox#53]
### What feature?

Funding is enabled on the repository but the FUNDING.yml file is not added not allowing for it to work

### Record

- [X] I have checked the existing [issues](https://github.com/FrancescoXX/contentbox/issues)
- [X] I want to work on this issue

**Comment by xkrishguptaa** [comment]
I would like to be assigned

**Comment by FrancescoXX** [comment]
assigned
