### ISSUE TITLE
feat: rename Linkfree to "BioDrop" in the footer section

### ISSUE THREAD

**Issue by FrancescoXX** [FrancescoXX/contentbox#56]
### What feature?

rename Linkfree to "BioDrop" in the footer section

### Add screenshots

![image](https://github.com/FrancescoXX/contentbox/assets/18360871/f0f6e5cd-0735-4956-b8bc-1ef26c9ef17f)

### Record

- [X] I have checked the existing [issues](https://github.com/FrancescoXX/contentbox/issues)
- [ ] I want to work on this issue

**Comment by Arindam200** [comment]
Can I work on this?

**Comment by FrancescoXX** [comment]
fixed #58
