### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by priyankarpal** [FrancescoXX/contentbox#6]
there are lots of important options that we need to allow such 

- Always suggest updating pull request branches 
- only Allow squash merging
- etc

**Comment by FrancescoXX** [comment]
each issue should ask foor one and only one thing

**Comment by priyankarpal** [comment]
> each issue should ask foor one and only one thing

please go to repo setting & you will find all options

![image](https://github.com/FrancescoXX/contentbox/assets/88102392/400797a5-125a-41f2-b127-52dddb3dfd0d)

**Comment by FrancescoXX** [comment]
done
